spring:
  application:
    name: jieax-backend
  datasource:
    druid:
      # 初始化链接
      initial-size: 5
      # 最小连接池数量
      min-idle: 5
      # 最大连接池数量
      max-active: 20
      # 获取连接超时时间
      max-wait: 600000
      # 检测需要关闭连接的时间间隔
      time-between-eviction-runs-millis: 600000
      # 连接在连接池中生存的最小时间
      min-evictable-idle-time-millis: 300000
      # 检测连接是否生效
      validation-query: SELECT 1 FROM dual
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
      username: ${SPRING_DATA_MONGODB_USERNAME}
      password: ${SPRING_DATA_MONGODB_PASSWORD}
server:
  port: 9090
